# Generated by Django 2.2.4 on 2022-01-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_person_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ФИО', max_length=15)),
                ('dict', models.CharField(blank=True, help_text='Район', max_length=230)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('bio', models.CharField(blank=True, help_text='О себе', max_length=230)),
                ('active', models.BooleanField(default=True, help_text='Работает')),
            ],
        ),
    ]
