# Generated by Django 2.2.4 on 2022-01-16 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_electric'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя леса', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название дерева', max_length=15)),
                ('height', models.IntegerField()),
                ('forest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Forest')),
            ],
        ),
    ]
