# Generated by Django 2.2.4 on 2022-01-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_forest_tree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Название жука')),
                ('population', models.IntegerField(verbose_name='Популяция')),
            ],
        ),
        migrations.AlterField(
            model_name='forest',
            name='name',
            field=models.CharField(help_text='Имя леса', max_length=15, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='name',
            field=models.CharField(help_text='Название дерева', max_length=15, verbose_name='Название дерева'),
        ),
        migrations.CreateModel(
            name='Bush',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Название куста')),
                ('bugs', models.ManyToManyField(to='firstapp.Bug')),
            ],
        ),
    ]
