# Generated by Django 2.2.4 on 2022-01-31 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20220120_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Имя')),
            ],
        ),
        migrations.AlterModelOptions(
            name='bug',
            options={'ordering': ['population']},
        ),
        migrations.AlterModelOptions(
            name='bush',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='TypeMoss',
            fields=[
                ('type_moss', models.CharField(max_length=15, verbose_name='Тип мха')),
                ('moss', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='firstapp.Moss')),
            ],
        ),
    ]
