# Generated by Django 2.2.4 on 2022-01-03 01:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211208_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 3, 1, 16, 43, 858069, tzinfo=utc)),
        ),
    ]
