# Generated by Django 2.2.4 on 2022-01-16 04:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220103_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 16, 4, 50, 12, 757515, tzinfo=utc)),
        ),
    ]
