# Generated by Django 2.2.4 on 2022-01-20 16:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220116_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 20, 16, 29, 12, 447194, tzinfo=utc)),
        ),
    ]
