# Generated by Django 2.2.4 on 2022-01-31 16:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20220120_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 31, 16, 49, 33, 846411, tzinfo=utc)),
        ),
    ]
