# Generated by Django 2.2.4 on 2022-02-05 17:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20220131_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 5, 17, 43, 3, 884616, tzinfo=utc)),
        ),
    ]
