# Generated by Django 2.2.4 on 2022-02-05 17:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220206_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 5, 17, 44, 57, 464671, tzinfo=utc)),
        ),
    ]
