# Generated by Django 2.2.4 on 2022-02-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(help_text='Выберете автора книги', to='catalog.Author', verbose_name='Автор книги'),
        ),
    ]
