# Generated by Django 2.2.4 on 2022-02-05 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20220206_0044'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookInstanse',
            new_name='BookInstance',
        ),
    ]
